version: "2.4"

services:
  caddy:
    depends_on:
      - mattermost
    container_name: mattermost-caddy
    build:
      context: .
      dockerfile: Dockerfile.caddy
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    ports:
      - ${HTTPS_PORT}:443
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - ${CADDY_DATA_PATH}/data:/data
      - ${CADDY_DATA_PATH}/config:/config
      - ${CADDY_DATA_PATH}/logs:/logs
    environment:
      # timezone inside container
      - TZ

configs:
  Caddyfile:
    content: |
      ${DOMAIN} {
        @denied not client_ip $CDN_IPV4 $CDN_IPV6 127.0.0.1 fd00::/8 ::1
        abort @denied

        reverse_proxy mattermost:${APP_PORT}
        tls {
          dns cloudflare ${CLOUDFLARE_API_TOKEN}
          on_demand
        }
        log {
          format console
          output file /logs/mattermost.log {
            roll_size 10mb
            roll_keep 20
            roll_keep_for 7d
          }
        }
        encode zstd gzip
      }
